[package]
name = "rapla"
version = "0.1.1"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1.25.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
futures = "0.3.26"

axum = "0.6.7"
tower-http = { version = "0.4.0", features = ["trace"] }

ics = "0.5.8"
chrono = "0.4.23"

reqwest = { version = "0.11.14", features = [
    "rustls-tls",
    "trust-dns",
], default-features = false }
scraper = "0.15.0"

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

anyhow = "1.0.69"
once_cell = "1.17.0"

[profile.release]
lto = true
opt-level = 3
strip = "symbols"
