[package]
name = "rapla"
version = "0.1.1"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1.25.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
futures = "0.3.26"

axum = "0.6.7"

ics = "0.5.8"
chrono = "0.4.23"

reqwest = { version = "0.11.14", features = [
    "rustls-tls",
    "trust-dns",
], default-features = false }
scraper = "0.14.0"

anyhow = "1.0.69"
once_cell = "1.17.0"

log = "0.4.17"
pretty_env_logger = "0.4.0"

[profile.release]
lto = true
opt-level = 3
strip = "symbols"
