[package]
name = "rapla-to-ics"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/satoqz/rapla-to-ics"
license = "MIT"
description = "Convert DHBW Rapla timetables to iCalendar, serverless"

[dependencies]
async-std = { version ="1.12.0", features = ["attributes"] }
futures = "0.3.1"
surf = { version = "2.3.2", features = ["h1-client-rustls"], default-features = false }
tide = "0.16.0"
scraper = "0.13.0"
chrono = "0.4.12"
ics = "0.5.7"
json_env_logger = "0.1.1"

[profile.release]
opt-level = "s"
lto = true
strip = "symbols"